/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  // englishSidebar: [
  //   'english/english',
  //   {
  //     type: 'category',
  //     label: 'ee單字/ee単語',
  //     items: ['english/word'],
  //   },
  // ],
  japaneseSidebar: [
    'japanese/japanese',
    {
      type: 'category',
      label: '單字/単語',
      items: ['japanese/word'],
    },
    {
      type: 'category',
      label: '句子/文',
      items: ['japanese/sentences/presentation'],
    },
  ],


};

module.exports = sidebars;
